name: name test
on:  [push]
jobs:
  name-test:
    runs-on: ubuntu-latest
    steps:
      - name: Runner Info
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ Now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” Branch is ${{ github.ref }} ${{ github.repository }} repo"
          echo "ğŸ’¡ The ${{ github.repository }} repo has been cloned to the runner."

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Sushi
        run:  |
          npm install
          gem install jekyll
          npm run sushi
          npm run ig_init
