name: name test
on:  [push]
jobs:
  name-teset:
    runs-on: ubuntu-latest
    - name: Runner Info
      steps:
        - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
        - run: echo "ğŸ§ Now running on a ${{ runner.os }} server hosted by GitHub!"
        - run: echo "ğŸ” Branch is ${{ github.ref }} ${{ github.repository }} repo"
        - run: echo "ğŸ’¡ The ${{ github.repository }} repo has been cloned to the runner."