name: Build And Publish v3
on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-publish-3:
    runs-on: ubuntu-latest
    steps:
      - name: Runner Info
        run: |
          echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
          echo "ğŸ§ Now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "ğŸ” Branch is ${{ github.ref }} ${{ github.repository }} repo"
          echo "ğŸ’¡ The ${{ github.repository }} repo has been cloned to the runner."
          echo "The event is ${{ github.event }}"
          echo "The event.pull_request.merged is ${{ github.event.pull_request.merged}}"
          echo "The base_ref is ${{ github.base_ref }}"
          echo "The head_ref is ${{ github.head_ref }}"

      - name: ECHO - ONLY ON MERGED PR
        if: github.event.pull_request.merged && github.ref == 'master'
        run: echo "My PR was merged, run this now!"

      - name: Checkout Repo
        uses: actions/checkout@v2

#      - name: Setup Ruby
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '3'
#          bundler-cache: true   # Runs 'bundle install' and caches installed gems automatically

#      - name: Setup Java / Maven
#        uses: actions/setup-java@v2
#        with:
#          java-version: '8'
#          distribution: 'adopt'          

      - name: Install Dependencies
        run:  |
          npm install
#          gem install jekyll
#          mvn clean install
#
      - name: Build IG
        run:  |
          npm run sushi
#          npm run ig_init
#
#      - name: Create Snapshot Jar
#        run:  |
#          npm run mvn_snapshot
#          npm run copy_snapshot
#
#      - name: Deploy gh-pages
#        if: github.ref == 'refs/heads/master'
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages      # The branch to deploy to
#          folder: build/output  # Folder to deploy
#
#      - name: Copy To Documents Folder
#      - run: npm run copy_docs_version
#
#      - name: Commit Changes
#        run: |
#          git config user.name github-actions
#          git config user.email github.actions@github.com
#          git add .
#          git commit -m "Generated docs"
#          git push          
