name: run sushi
on:  [push]
jobs:
  run-sushi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ Now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” Branch is ${{ github.ref }} ${{ github.repository }} repo"
      - run: echo "ğŸ’¡ The ${{ github.repository }} repo has been cloned to the runner."
      - run: npm install
      - run: gem install jekyll
      - run: npm run sushi
      - run: npm run ig_init
      - run: npm run copy_version
      - run: |
          git config user.name github-actions
          git config user.email github.actions@github.com
          git add .
          git commit -m "Generated docs"
          git push
#      - run: mkdir -p ./src/main/resources/com/ibm/fhir/cdm
#            && tar -C ./src/main/resources/com/ibm/fhir/cdm/ -xf ./build/output/package.tgz 
#            && mvn test
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      