name: run sushi
on: [push]
jobs:
  Run-Sushi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: '14'
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3'
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

#      - name: Check out repository code
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      
      - name: Install Sushi and Jekyll
      - run: npm install
      - run: gem install jekyll

      - name: Run Sushi and build the IG
      - run: npm run sushi
      - run: yes | npm run ig_init

      - run: echo "ğŸ This job's status is ${{ job.status }}."